# -*- coding: utf-8 -*-
"""Copy of Copy of Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/FIT3164Group1/Project/blob/main/Model.ipynb
"""
# Get image from HTML
import dash
from dash.dependencies import Input, Output, State
import dash_core_components as dcc
import dash_html_components as html


external_stylesheets = ['custom.css']
app = dash.Dash(__name__, external_stylesheets=external_stylesheets, external_scripts=[{"src": "custom.js"}])
#external_stylesheets = ['tailwind.css']
#app = dash.Dash(__name__, external_stylesheets=external_stylesheets, external_scripts=[{"src": "tailwind.config.js"}])



app.layout = html.Div([
   dcc.Upload(
        id='upload_image',
        children=html.Div([
            'Drag and Drop or ',
            html.A('Select Files')
        ]),
        style={
            'width': '100%',
            'height': '60px',
            'lineHeight': '60px',
            'borderWidth': '1px',
            'borderStyle': 'dashed',
            'borderRadius': '5px',
            'textAlign': 'center',
            'margin': '10px'
        },
        # Allow multiple files to be uploaded
        multiple=False
    ),
    dcc.Store(id='store', data={}),
    html.Div(id='pythoned', children=''),
])


@app.callback(
    Output('pythoned', 'children'),
    Input('store', 'data'),
)

def update_store_data(data):
    print(data)
    return data


app.clientside_callback(
    """
    function(text) {
        return text;
    }
    """,
    Output('store', 'data'),
    Input('upload_image', 'contents'),
    prevent_initial_call=True
)


if __name__ == '__main__':
    app.run_server(debug=True, port=5559)

