# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fz52y0JAM2k1-IJ4FYzxmIoBDlQqiAe-
"""

import math

import random

import tensorflow

